# Generated by Django 5.1.1 on 2025-05-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleModel',
        ),
    ]
